### ISSUE TITLE
Ошибка при запуске скрипта

### ISSUE THREAD

**Issue by psyapathy** [nextgis/reformagkh#16]
Добрый день. Настроил всё по инструкции.
Пытаюсь запустить,получаю ошибку. ID в atd.csv присутствует.

gkh>python get_reformagkh_myhouse.py 2227650 vlggg.csv -of html
Волгоградская область, Иловлинский муниципальный район, Иловлинское
Traceback (most recent call last):                     ] 0 of 50 ETA:  --:--:--
  File "get_reformagkh_myhouse.py", line 399, in <module>
    res = get_housedata(house_link,str(house_id),reg[0],reg[3],reg[1],reg[4])
  File "get_reformagkh_myhouse.py", line 252, in get_housedata
    lat,lon = soup.findAll('script')[12].text.split('\n')[3].split('[')[1].split(']')[0].split(',')
IndexError: list index out of range

**Comment by simgislab** [comment]
значит в очередной раз изменился сайт РеформыЖКХ

**Comment by psyapathy** [comment]
Жаль..Спасибо за ответ.
Хотел попробовать запустить на Python 3 еще. Там набор модулей аналогичный? requesocks есть для Python 3?

Подскажите еще пожалуйста что за скрипты в папке Old?

**Comment by psyapathy** [comment]
Еще вот это:
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>

**Comment by simgislab** [comment]
код открыт, изучайте, исправляйте
мы перешли на другую систему выгрузки данных и эту больше поддерживать не планируем

если вам нужна конкретная выгрузка, можете заказать у нас info@nextgis.com

**Comment by AlSeUs** [comment]
Понимаю, что наглость, но кто-нибудь смог решить эту проблему?)
К сожалению моих знаний не хватило(

**Comment by AlSeUs** [comment]
нашел проблему. она касалась поиска координат дома.
решение - убрать строчки
` #TODO extract lat/long coords from script
            if 'center' in soup.findAll('script')[11]:
                lat,lon = soup.findAll('script')[11].text.split('\n')[3].split('[')[1].split(']')[0].split(',')
            else:
                lat,lon = soup.findAll('script')[12].text.split('\n')[3].split('[')[1].split(']')[0].split(',')`

и заменить их на пустоты в данном месте
```
csvwriter_housedata.writerow(dict(result,
                                              LAT='',
                                              LON=''
```
