### ISSUE TITLE
Какая-то проблема.

### ISSUE THREAD

**Issue by berpcor** [nextgis/reformagkh#8]
```
Traceback (most recent call last):                      ] 0 of 0 ETA:  --:--:--         
  File "C:\Reforma\get_reformagkh_data-v2.py", line 322, in <module>                    
    pbar.finish()                                                                       
  File "build\bdist.win32\egg\progressbar\__init__.py", line 320, in finish             
  File "build\bdist.win32\egg\progressbar\__init__.py", line 283, in update             
  File "build\bdist.win32\egg\progressbar\__init__.py", line 243, in _format_line       
  File "build\bdist.win32\egg\progressbar\__init__.py", line 233, in _format_widgets    
  File "build\bdist.win32\egg\progressbar\widgets.py", line 261, in update              
ZeroDivisionError: division by zero     
```

Вчера работало, сегодня отказывается.

**Comment by simgislab** [comment]
вас забанили на сайте реформы, введите капчу, это разбанит

но потом вас снова забанят
