### ISSUE TITLE
Неизвестная ошибка

### ISSUE THREAD

**Issue by berpcor** [nextgis/reformagkh#9]
```
Traceback (most recent call last):                   ] 112 of 610 ETA:  0:24:34
  File "C:\Reforma\get_reformagkh_data-v2.py", line 320, in <module>
    res = get_housedata(house_link,str(house_id),reg[0],reg[3],reg[1],reg[4])
  File "C:\Reforma\get_reformagkh_data-v2.py", line 160, in get_housedata
    res = urlopen_house(link + 'view/' + house_id,house_id)
  File "C:\Reforma\get_reformagkh_data-v2.py", line 107, in urlopen_house
    f = open(args.originals_folder + id + ".html","wb")
IOError: [Errno 22] invalid mode ('wb') or filename: 'html\\8926902.html'
```
И так может высыпать на любом по счету объекте. Обиднее всего, когда на каком-нибудь 550-м из 610. За два дня так и не смог выкачать всю информацию, прерывается.

**Comment by simgislab** [comment]
возможно тоже из-за капчи, только не ясно как именно и как отлаживать

я  там все переделал на самом деле, как-нибудь выложу новую версию

**Comment by berpcor** [comment]
Фактически, ведь это недолго. У вас есть возможность выложить новую версию... например, сейчас?..

**Comment by berpcor** [comment]
Получилось таки дождаться, пока завершится работа. Но data/housedata.csv почему-то пустой, только заголовки столбцов.

**Comment by simgislab** [comment]
используйте новый скрипт

**Comment by berpcor** [comment]
Спасибо.

**Comment by berpcor** [comment]
```
Traceback (most recent call last):
  File "C:\Reforma\get_reformagkh_data-v3.py", line 337, in <module>
    houses_ids = get_house_list('http://www.reformagkh.ru/myhouse/list?tid=' + reg[4])
  File "C:\Reforma\get_reformagkh_data-v3.py", line 134, in get_house_list
    size = check_size(link)
  File "C:\Reforma\get_reformagkh_data-v3.py", line 117, in check_size
    res = get_content(link)
  File "C:\Reforma\get_reformagkh_data-v3.py", line 83, in get_content
    return res
UnboundLocalError: local variable 'res' referenced before assignment
```

**Comment by simgislab** [comment]
https://github.com/nextgis/reformagkh#%D0%9A%D0%B0%D0%BA-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%B0%D1%82%D1%8C

**Comment by berpcor** [comment]
И снова ошибка. Ссылка, которую вы дали. Там неверно указана команда для запуска.

```
get_reformagkh_data-v3.py [my_region_number] data/housedata.csv -o html
usage: get_reformagkh_data-v3.py [-h] [-o] [-of ORIGINALS_FOLDER]
                                 id output_name
get_reformagkh_data-v3.py: error: unrecognized arguments: html
```

**Comment by berpcor** [comment]
Если делать все по инструкции, то...

```
get_reformagkh_data-v3.py [id] -o data/housedata.csv -of html
... край, город ...,
Traceback (most recent call last):
  File "C:\Reforma\get_reformagkh_data-v3.py", line 337, in <module>
    houses_ids = get_house_list('http://www.reformagkh.ru/myhouse/list?tid=' + reg[4])
  File "C:\Reforma\get_reformagkh_data-v3.py", line 134, in get_house_list
    size = check_size(link)
  File "C:\Reforma\get_reformagkh_data-v3.py", line 117, in check_size
    res = get_content(link)
  File "C:\Reforma\get_reformagkh_data-v3.py", line 83, in get_content
    return res
UnboundLocalError: local variable 'res' referenced before assignment
```
